name: Rake Build and Test

on:
  pull_request:
  schedule:
    - cron: '0 2 * * 0'  # Every Sunday at 11:00 JST

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Run rubocop
        run: bundle exec rubocop

  build-test:
    runs-on: ubuntu-latest
    needs: rubocop
    strategy:
      matrix:
        mruby_version: [master, 3.4.0]
    env:
      MRUBY_VERSION: ${{ matrix.mruby_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Run rake build and test
        run: rake test

  all-builds:
    runs-on: ubuntu-latest
    needs: build-test
    if: always()
    steps:
      - name: Check matrix results
        run: |
          if [ "${{ needs.build-test.result }}" != "success" ]; then
            echo "Some matrix jobs failed"
            exit 1
          fi
      - name: All build-test matrix jobs completed
        run: echo "All build-test matrix jobs completed."
